// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/article/[page].tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/p/[id].tsx";
import * as $$0 from "./islands/ShareButton.tsx";

const manifest = {
  routes: {
    "./routes/article/[page].tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/p/[id].tsx": $2,
  },
  islands: {
    "./islands/ShareButton.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
